use std::collections::HashSet;

use fallible_iterator::FallibleIterator;

use crate::{
    TransactionId, Value,
    catalog::{CatalogError, ConstraintDef, TableInfo, manager::Catalog, systable::FkAction},
    engine::{ConstraintViolation, Engine, EngineError},
    execution::expression::BooleanExpression,
    heap::file::HeapFile,
    parser::statements::TableConstraint,
    primitives::{ColumnId, NonEmptyString, RecordId},
    transaction::Transaction,
    tuple::{Field, Tuple, TupleSchema},
};

impl Engine<'_> {
    /// Ensures that all string elements in an iterator are unique.
    ///
    /// Iterates through the provided items, checking for duplicate strings. If a duplicate is
    /// found, returns a [`EngineError`] generated by calling `dup_err` with the offending string
    /// as argument. Returns `Ok(())` if all strings are unique.
    ///
    /// This is a utility for ensuring, at bind time, that a list of column or identifier names
    /// does not contain any duplicates (for example, in a CREATE TABLE or CREATE INDEX column
    /// list).
    ///
    /// # Parameters
    ///
    /// - `items`: An iterator over string slices to check for uniqueness.
    /// - `dup_err`: A closure invoked to construct a [`EngineError`] when a duplicate is found.
    ///
    /// # Errors
    ///
    /// Returns the result of calling `dup_err` on the first duplicate encountered.
    pub(super) fn ensure_unique_strs<'a, I, F>(items: I, dup_err: F) -> Result<(), EngineError>
    where
        I: IntoIterator<Item = &'a str>,
        F: Fn(&'a str) -> EngineError,
    {
        let iter = items.into_iter();
        let (lower, _) = iter.size_hint();
        let mut seen = HashSet::with_capacity(lower);

        for s in iter {
            if !seen.insert(s) {
                return Err(dup_err(s));
            }
        }
        Ok(())
    }

    /// Shared catalog lookup for DDL that names a table (`ON users`, `FROM users`, `DROP TABLE
    /// users`).
    ///
    /// Maps [`CatalogError::TableNotFound`] to
    /// [`EngineError::TableNotFound`]; other catalog errors become
    /// [`EngineError::Catalog`].
    ///
    /// # Errors
    ///
    /// - [`EngineError::TableNotFound`] — no such table.
    /// - [`EngineError::Catalog`] — other catalog read failures.
    pub(super) fn check_table(
        catalog: &Catalog,
        txn: &Transaction<'_>,
        table_name: &str,
        if_exists: bool,
    ) -> Result<Option<TableInfo>, EngineError> {
        let info = match catalog.get_table_info(txn, table_name) {
            Ok(info) => info,
            Err(CatalogError::TableNotFound { table_name }) => {
                return if if_exists {
                    Ok(None)
                } else {
                    Err(EngineError::TableNotFound(table_name.to_string()))
                };
            }
            Err(other) => return Err(other.into()),
        };
        Ok(Some(info))
    }

    /// Resolves a list of column names to their corresponding column IDs in a given table schema.
    ///
    /// This function checks that all column names in `columns` are unique, then looks up each
    /// column name in the provided `schema`. If all columns exist and are unique, their
    /// `ColumnId`s are returned in the same order. This is commonly used during query binding
    /// and validation to convert user-supplied column names into internal identifiers.
    ///
    /// # Errors
    ///
    /// - Returns [`EngineError::DuplicateColumn`] if there are any duplicate column names in the
    ///   input.
    /// - Returns [`EngineError::UnknownColumn`] if any column does not exist in the schema.
    pub(super) fn resolve_column_ids<'a, I>(
        schema: &TupleSchema,
        table_name: &str,
        columns: I,
    ) -> Result<Vec<ColumnId>, EngineError>
    where
        I: IntoIterator<Item = &'a NonEmptyString>,
    {
        let columns = columns.into_iter().collect::<Vec<_>>();
        Self::ensure_unique_strs(columns.iter().map(|c| c.as_str()), |column| {
            EngineError::DuplicateColumn {
                table: table_name.to_string(),
                column: column.to_string(),
            }
        })?;

        columns
            .into_iter()
            .map(|c| Self::require_column(schema, table_name, c).map(|(id, _)| id))
            .collect()
    }

    /// Looks up a column in a schema by name, returning the column's ID and field definition.
    ///
    /// Used during binding to ensure a column reference is valid and to retrieve its schema info.
    ///
    /// # Arguments
    ///
    /// * `schema` - The tuple schema to search.
    /// * `table` - The name of the table (for error reporting).
    /// * `column` - The name of the column to look up.
    ///
    /// # Errors
    ///
    /// Returns [`EngineError::UnknownColumn`] if the column is not found in the schema.
    pub(super) fn require_column<'s>(
        schema: &'s TupleSchema,
        table: &str,
        column: &str,
    ) -> Result<(ColumnId, &'s Field), EngineError> {
        schema
            .field_by_name(column)
            .ok_or_else(|| EngineError::UnknownColumn {
                table: table.to_string(),
                column: column.to_string(),
            })
    }

    /// Converts a parsed table-level constraint into a catalog [`ConstraintDef`].
    ///
    /// This is used when materializing `CREATE TABLE ...` constraints into the catalog layer.
    /// It validates that all referenced columns exist in the provided `schema` (for local
    /// columns) and, for foreign keys, in the referenced table's schema fetched from `catalog`.
    ///
    /// If the SQL did not provide an explicit constraint name, a stable default is generated:
    ///
    /// - `UNIQUE (a, b)` → `{table}_unique_a_b`
    /// - `CHECK (...)` → `{table}_check`
    /// - `FOREIGN KEY (a, b) ...` → `{table}_fk_a_b`
    ///
    /// # Errors
    ///
    /// - [`EngineError::TableNotFound`] — referenced table for a foreign key does not exist.
    /// - [`EngineError::UnknownColumn`] — a referenced column does not exist (local or referenced).
    /// - [`EngineError::DuplicateColumn`] — the same column name appears more than once in a column
    ///   list.
    /// - [`EngineError::Unsupported`] — foreign key local/ref column counts differ.
    pub(super) fn resolve_table_constraint(
        catalog: &Catalog,
        txn: &Transaction<'_>,
        constraint: &(Option<NonEmptyString>, TableConstraint),
        schema: &TupleSchema,
        table_name: &str,
    ) -> Result<ConstraintDef, EngineError> {
        let (opt_name, constraint) = constraint;
        let def = match constraint {
            TableConstraint::Unique { columns: col_names } => {
                let columns = Self::resolve_column_ids(schema, table_name, col_names.as_slice())?;
                ConstraintDef::Unique {
                    name: Self::resolve_constraint_name(opt_name.as_ref(), table_name, constraint),
                    columns,
                    backing_index_id: None,
                }
            }
            TableConstraint::Check { expr } => ConstraintDef::Check {
                name: Self::resolve_constraint_name(opt_name.as_ref(), table_name, constraint),
                expr: expr.to_string(),
            },
            TableConstraint::ForeignKey {
                local_cols,
                ref_table,
                ref_cols,
                on_delete,
                on_update,
            } => {
                let local_columns =
                    Self::resolve_column_ids(schema, table_name, local_cols.as_slice())?;

                let ref_info = Self::check_table(catalog, txn, ref_table.as_str(), false)?
                    .expect("if_exists=false never yields None");

                let ref_ids = Self::resolve_column_ids(
                    &ref_info.schema,
                    ref_info.name.as_str(),
                    ref_cols.as_slice(),
                )?;

                if ref_ids.len() != local_columns.len() {
                    return Err(EngineError::Unsupported(format!(
                        "foreign key column count mismatch: {} local columns, {} referenced columns",
                        local_columns.len(),
                        ref_ids.len()
                    )));
                }

                ConstraintDef::ForeignKey {
                    name: Self::resolve_constraint_name(opt_name.as_ref(), table_name, constraint),
                    local_columns,
                    ref_table_id: ref_info.file_id,
                    ref_columns: ref_ids,
                    on_delete: on_delete.map(FkAction::from),
                    on_update: on_update.map(FkAction::from),
                }
            }
        };
        Ok(def)
    }

    /// Picks a catalog constraint name for a table-level constraint.
    ///
    /// If the user provided a name (via `CONSTRAINT name ...`), that name is returned.
    /// Otherwise, a deterministic default is derived from the table name and constraint kind:
    ///
    /// - `UNIQUE (a, b)` → `{table}_unique_a_b`
    /// - `CHECK (...)` → `{table}_check`
    /// - `FOREIGN KEY (a, b) ...` → `{table}_fk_a_b`
    ///
    /// Note: these generated names are stable but not guaranteed globally unique (e.g. two
    /// separate `CHECK` constraints on the same table both default to `{table}_check`).
    pub(super) fn resolve_constraint_name(
        opt_name: Option<&NonEmptyString>,
        table_name: &str,
        constraint: &TableConstraint,
    ) -> String {
        if let Some(name) = opt_name {
            return name.as_str().to_owned();
        }

        match constraint {
            TableConstraint::Unique { columns } => {
                let cols = columns.join("_");
                format!("{table_name}_unique_{cols}")
            }
            TableConstraint::Check { .. } => format!("{table_name}_check"),
            TableConstraint::ForeignKey { local_cols, .. } => {
                let cols = local_cols.join("_");
                format!("{table_name}_fk_{cols}")
            }
        }
    }

    /// Collects every heap row visible to `transaction_id`, optionally filtered by `predicate`.
    ///
    /// Rows with no predicate are included. When `predicate` is `Some`, a row is kept only if the
    /// expression evaluates to true for that row's tuple.
    ///
    /// # Errors
    ///
    /// Returns [`EngineError`] if the heap scan cannot advance.
    ///
    /// # Examples
    ///
    /// Collect all rows without filtering:
    ///
    /// ```ignore
    /// let rows = collect_matching(&heap, txn_id, None)?;
    /// // rows contains every (RecordId, Tuple) pair visible to the transaction
    /// ```
    ///
    /// Collect only rows where the first column equals `42`:
    ///
    /// ```ignore
    /// use storemy::{execution::expression::BooleanExpression, primitives::Predicate, types::Value};
    ///
    /// let predicate = BooleanExpression::col_op_lit(0, Predicate::Equals, Value::Int32(42));
    /// let rows = collect_matching(&heap, txn_id, Some(&predicate))?;
    /// // rows contains only tuples whose first column is 42
    /// ```
    pub(super) fn collect_matching_rows(
        heap: &HeapFile,
        transaction_id: TransactionId,
        predicate: Option<&BooleanExpression>,
    ) -> Result<Vec<(RecordId, Tuple)>, EngineError> {
        let mut scan = heap.scan(transaction_id)?;
        let mut out = Vec::new();

        while let Some((rid, tuple)) = FallibleIterator::next(&mut scan)? {
            let keep = match predicate {
                None => true,
                Some(p) => p
                    .eval(&tuple)
                    .map_err(|e| EngineError::TypeError(e.to_string()))?,
            };
            if keep {
                out.push((rid, tuple));
            }
        }
        Ok(out)
    }

    /// Enforces all column-level constraints for a single value before it is written.
    ///
    /// Currently checks:
    /// - **NOT NULL** — rejects [`Value::Null`] when the field is not nullable.
    ///
    /// Future constraints to add here:
    /// - CHECK expressions (e.g. `price > 0`) — evaluate the expression against the value and
    ///   return [`ConstraintViolation::CheckViolation`] on failure.
    ///
    /// # Errors
    ///
    /// - [`ConstraintViolation::NullViolation`] if a null is supplied for a `NOT NULL` column.
    pub(super) fn check_column_constraints(
        value: &Value,
        field: &Field,
        table: &str,
    ) -> Result<(), EngineError> {
        // NOT NULL
        if matches!(value, Value::Null) && !field.nullable {
            return Err(ConstraintViolation::NullViolation {
                table: table.into(),
                column: field.name.to_string(),
            }
            .into());
        }

        // TODO: CHECK constraints — evaluate field.check_expr against `value` here.

        Ok(())
    }

    /// Coerces a literal [`Value`] to the type declared by a table column ([`Field`]).
    ///
    /// Enforces column-level constraints via [`Self::check_column_constraints`] first, then
    /// converts the value to the column's declared type. Returns [`Value::Null`] unchanged for
    /// nullable columns.
    ///
    /// # Errors
    ///
    /// - [`ConstraintViolation::NullViolation`] if a null value is bound to a non-nullable column.
    /// - [`EngineError::TypeMismatch`] if the value cannot be coerced to the column type.
    pub(super) fn fit_value_to_field(
        value: &Value,
        field: &Field,
        table: &str,
    ) -> Result<Value, EngineError> {
        Self::check_column_constraints(value, field, table)?;

        if matches!(value, Value::Null) {
            return Ok(Value::Null);
        }

        Value::try_from((value, field.field_type)).map_err(|e| EngineError::TypeMismatch {
            column: field.name.to_string(),
            expected: field.field_type.to_string(),
            got: e.to_string(),
        })
    }
}
