use std::collections::HashSet;

use crate::{
    catalog::{CatalogError, TableInfo, manager::Catalog},
    engine::{Engine, EngineError},
    primitives::ColumnId,
    transaction::Transaction,
    tuple::{Field, TupleSchema},
};

impl Engine<'_> {
    /// Ensures that all string elements in an iterator are unique.
    ///
    /// Iterates through the provided items, checking for duplicate strings. If a duplicate is
    /// found, returns a [`EngineError`] generated by calling `dup_err` with the offending string
    /// as argument. Returns `Ok(())` if all strings are unique.
    ///
    /// This is a utility for ensuring, at bind time, that a list of column or identifier names
    /// does not contain any duplicates (for example, in a CREATE TABLE or CREATE INDEX column
    /// list).
    ///
    /// # Parameters
    ///
    /// - `items`: An iterator over string slices to check for uniqueness.
    /// - `dup_err`: A closure invoked to construct a [`EngineError`] when a duplicate is found.
    ///
    /// # Errors
    ///
    /// Returns the result of calling `dup_err` on the first duplicate encountered.
    pub(super) fn ensure_unique_strs<'a, I, F>(items: I, dup_err: F) -> Result<(), EngineError>
    where
        I: IntoIterator<Item = &'a str>,
        F: Fn(&'a str) -> EngineError,
    {
        let iter = items.into_iter();
        let (lower, _) = iter.size_hint();
        let mut seen = HashSet::with_capacity(lower);

        for s in iter {
            if !seen.insert(s) {
                return Err(dup_err(s));
            }
        }
        Ok(())
    }

    /// Shared catalog lookup for DDL that names a table (`ON users`, `FROM users`, `DROP TABLE
    /// users`).
    ///
    /// Maps [`CatalogError::TableNotFound`] to
    /// [`EngineError::UnknownTable`]; other catalog errors become
    /// [`EngineError::Catalog`].
    ///
    /// # Errors
    ///
    /// - [`EngineError::UnknownTable`] — no such table.
    /// - [`EngineError::Catalog`] — other catalog read failures.
    pub(super) fn check_table(
        catalog: &Catalog,
        txn: &Transaction<'_>,
        table_name: &str,
        if_exists: bool,
    ) -> Result<Option<TableInfo>, EngineError> {
        let info = match catalog.get_table_info(txn, table_name) {
            Ok(info) => info,
            Err(CatalogError::TableNotFound { table_name }) => {
                return if if_exists {
                    Ok(None)
                } else {
                    Err(EngineError::UnknownTable(table_name.to_string()))
                };
            }
            Err(other) => return Err(other.into()),
        };
        Ok(Some(info))
    }

    /// Resolves a list of column names to their corresponding column IDs in a given table schema.
    ///
    /// This function checks that all column names in `columns` are unique, then looks up each
    /// column name in the provided `schema`. If all columns exist and are unique, their
    /// `ColumnId`s are returned in the same order. This is commonly used during query binding
    /// and validation to convert user-supplied column names into internal identifiers.
    ///
    /// # Errors
    ///
    /// - Returns [`EngineError::DuplicateColumn`] if there are any duplicate column names in the
    ///   input.
    /// - Returns [`EngineError::UnknownColumn`] if any column does not exist in the schema.
    pub(super) fn resolve_column_ids<'a, I>(
        schema: &TupleSchema,
        table_name: &str,
        columns: I,
    ) -> Result<Vec<ColumnId>, EngineError>
    where
        I: IntoIterator<Item = &'a str>,
    {
        let columns = columns.into_iter().collect::<Vec<_>>();
        Self::ensure_unique_strs(columns.iter().copied(), |column| {
            EngineError::DuplicateColumn {
                table: table_name.to_string(),
                column: column.to_string(),
            }
        })?;

        columns
            .into_iter()
            .map(|c| Self::require_column(schema, table_name, c).map(|(id, _)| id))
            .collect()
    }

    /// Looks up a column in a schema by name, returning the column's ID and field definition.
    ///
    /// Used during binding to ensure a column reference is valid and to retrieve its schema info.
    ///
    /// # Arguments
    ///
    /// * `schema` - The tuple schema to search.
    /// * `table` - The name of the table (for error reporting).
    /// * `column` - The name of the column to look up.
    ///
    /// # Errors
    ///
    /// Returns [`EngineError::UnknownColumn`] if the column is not found in the schema.
    pub(super) fn require_column<'s>(
        schema: &'s TupleSchema,
        table: &str,
        column: &str,
    ) -> Result<(ColumnId, &'s Field), EngineError> {
        schema
            .field_by_name(column)
            .ok_or_else(|| EngineError::UnknownColumn {
                table: table.to_string(),
                column: column.to_string(),
            })
    }
}
