version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - prealloc
  disable:
    - exhaustruct
    - wrapcheck
    - godot
    - funlen
    - cyclop
    - gocognit
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
      disabled-checks:
        - commentedOutCode
        - hugeParam
        - rangeValCopy
    misspell:
      locale: US
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gocritic
      - path: pkg/examples/
        linters:
          - errcheck
      - linters:
          - staticcheck
        text: "SA1019"

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
