run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - prealloc
    - cyclop
    - gocognit

linters-settings:
  cyclop:
    max-complexity: 15
  gocognit:
    min-complexity: 30
  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - commentedOutCode
      - hugeParam
      - rangeValCopy
  misspell:
    locale: US
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - cyclop
        - gocognit
    - path: pkg/examples/
      linters:
        - errcheck
    - linters:
        - staticcheck
      text: "SA1019"
