use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenType {
    Create,
    Table,
    Drop,
    If,
    Not,
    Exists,
    Primary,
    Key,
    Default,
    Null,
    AutoIncrement,
    Select,
    Distinct,
    From,
    Where,
    Join,
    Inner,
    Left,
    Right,
    Outer,
    On,
    Group,
    Order,
    By,
    Limit,
    Offset,
    Index,
    Using,
    Hash,
    Btree,
    Union,
    Intersect,
    Except,
    All,

    Asc,
    Desc,
    And,
    Or,

    Insert,
    Into,
    Values,
    Update,
    Set,
    Delete,

    Begin,
    Commit,
    Rollback,
    Transaction,

    Explain,
    Analyze,
    Format,

    Show,
    Indexes,

    Int,
    Varchar,
    Text,
    Boolean,
    Float,
    Operator,
    String,
    Identifier,

    Comma,
    Semicolon,
    Lparen,
    Rparen,
    Asterisk,

    Invalid,
    Eof,
}

// 2. We use the `Display` trait instead of a runtime HashMap.
// This compiles down to a highly optimized jump table, requiring zero heap allocations.
impl fmt::Display for TokenType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            TokenType::Create => "CREATE",
            TokenType::Table => "TABLE",
            TokenType::Drop => "DROP",
            TokenType::If => "IF",
            TokenType::Not => "NOT",
            TokenType::Exists => "EXISTS",
            TokenType::Primary => "PRIMARY",
            TokenType::Key => "KEY",
            TokenType::Default => "DEFAULT",
            TokenType::Null => "NULL",
            TokenType::AutoIncrement => "AUTO_INCREMENT",
            TokenType::Select => "SELECT",
            TokenType::Distinct => "DISTINCT",
            TokenType::From => "FROM",
            TokenType::Where => "WHERE",
            TokenType::Join => "JOIN",
            TokenType::Inner => "INNER",
            TokenType::Left => "LEFT",
            TokenType::Right => "RIGHT",
            TokenType::Outer => "OUTER",
            TokenType::On => "ON",
            TokenType::Group => "GROUP",
            TokenType::Order => "ORDER",
            TokenType::By => "BY",
            TokenType::Limit => "LIMIT",
            TokenType::Offset => "OFFSET",
            TokenType::Index => "INDEX",
            TokenType::Using => "USING",
            TokenType::Hash => "HASH",
            TokenType::Btree => "BTREE",
            TokenType::Union => "UNION",
            TokenType::Intersect => "INTERSECT",
            TokenType::Except => "EXCEPT",
            TokenType::All => "ALL",
            TokenType::Asc => "ASC",
            TokenType::Desc => "DESC",
            TokenType::And => "AND",
            TokenType::Or => "OR",
            TokenType::Insert => "INSERT",
            TokenType::Into => "INTO",
            TokenType::Values => "VALUES",
            TokenType::Update => "UPDATE",
            TokenType::Set => "SET",
            TokenType::Delete => "DELETE",
            TokenType::Begin => "BEGIN",
            TokenType::Commit => "COMMIT",
            TokenType::Rollback => "ROLLBACK",
            TokenType::Transaction => "TRANSACTION",
            TokenType::Explain => "EXPLAIN",
            TokenType::Analyze => "ANALYZE",
            TokenType::Format => "FORMAT",
            TokenType::Show => "SHOW",
            TokenType::Indexes => "INDEXES",
            TokenType::Int => "INT",
            TokenType::Varchar => "VARCHAR",
            TokenType::Text => "TEXT",
            TokenType::Boolean => "BOOLEAN",
            TokenType::Float => "FLOAT",
            TokenType::Operator => "OPERATOR",
            TokenType::String => "STRING",
            TokenType::Identifier => "IDENTIFIER",
            TokenType::Comma => "COMMA",
            TokenType::Semicolon => "SEMICOLON",
            TokenType::Lparen => "LPAREN",
            TokenType::Rparen => "RPAREN",
            TokenType::Asterisk => "ASTERISK",
            TokenType::Invalid => "INVALID",
            TokenType::Eof => "EOF",
        };
        write!(f, "{}", s)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenType,
    pub value: String,
    pub position: usize,
}

impl std::str::FromStr for TokenType {
    type Err = &'static str;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let upper_s = s.to_ascii_uppercase();

        match upper_s.as_str() {
            "SELECT" => Ok(TokenType::Select),
            "DISTINCT" => Ok(TokenType::Distinct),
            "FROM" => Ok(TokenType::From),
            "WHERE" => Ok(TokenType::Where),
            "JOIN" => Ok(TokenType::Join),
            "INNER" => Ok(TokenType::Inner),
            "LEFT" => Ok(TokenType::Left),
            "RIGHT" => Ok(TokenType::Right),
            "OUTER" => Ok(TokenType::Outer),
            "ON" => Ok(TokenType::On),
            "GROUP" => Ok(TokenType::Group),
            "BY" => Ok(TokenType::By),
            "ORDER" => Ok(TokenType::Order),
            "LIMIT" => Ok(TokenType::Limit),
            "OFFSET" => Ok(TokenType::Offset),
            "ASC" => Ok(TokenType::Asc),
            "DESC" => Ok(TokenType::Desc),
            "AND" => Ok(TokenType::And),
            "OR" => Ok(TokenType::Or),
            "CREATE" => Ok(TokenType::Create),
            "TABLE" => Ok(TokenType::Table),
            "DROP" => Ok(TokenType::Drop),
            "IF" => Ok(TokenType::If),
            "NOT" => Ok(TokenType::Not),
            "EXISTS" => Ok(TokenType::Exists),
            "PRIMARY" => Ok(TokenType::Primary),
            "KEY" => Ok(TokenType::Key),
            "INDEX" => Ok(TokenType::Index),
            "USING" => Ok(TokenType::Using),
            "HASH" => Ok(TokenType::Hash),
            "BTREE" => Ok(TokenType::Btree),
            "UNION" => Ok(TokenType::Union),
            "INTERSECT" => Ok(TokenType::Intersect),
            "EXCEPT" => Ok(TokenType::Except),
            "ALL" => Ok(TokenType::All),
            "DEFAULT" => Ok(TokenType::Default),
            "NULL" => Ok(TokenType::Null),
            "AUTO_INCREMENT" => Ok(TokenType::AutoIncrement),
            "INSERT" => Ok(TokenType::Insert),
            "INTO" => Ok(TokenType::Into),
            "VALUES" => Ok(TokenType::Values),
            "UPDATE" => Ok(TokenType::Update),
            "SET" => Ok(TokenType::Set),
            "DELETE" => Ok(TokenType::Delete),
            "BEGIN" => Ok(TokenType::Begin),
            "COMMIT" => Ok(TokenType::Commit),
            "ROLLBACK" => Ok(TokenType::Rollback),
            "TRANSACTION" => Ok(TokenType::Transaction),
            "EXPLAIN" => Ok(TokenType::Explain),
            "ANALYZE" => Ok(TokenType::Analyze),
            "FORMAT" => Ok(TokenType::Format),
            "SHOW" => Ok(TokenType::Show),
            "INDEXES" => Ok(TokenType::Indexes),

            "INT" | "INTEGER" => Ok(TokenType::Int),
            "VARCHAR" | "STRING" => Ok(TokenType::Varchar),
            "TEXT" => Ok(TokenType::Text),
            "BOOLEAN" | "BOOL" => Ok(TokenType::Boolean),
            "FLOAT" | "REAL" | "DOUBLE" => Ok(TokenType::Float),

            _ => Err("Cannot find any keyword related to this"),
        }
    }
}
